global using System.Collections;
global using System.Numerics;
global using NUnit.Framework;
global using NSubstitute;
global using FluentAssertions;
global using SampSharp.Entities.SAMP;

global using CTF.Application.Common.Results;
global using CTF.Application.Common.Extensions;
global using CTF.Application.Players.Ranks;
global using CTF.Application.Players.Weapons;
global using CTF.Application.Players.Accounts;
global using CTF.Application.Players.Vitalities;
global using CTF.Application.Players.Extensions;
global using CTF.Application.Teams;
global using CTF.Application.Teams.Flags;
global using CTF.Application.Maps;
global using CTF.Application.Maps.Services;
global using CTF.Application.Tests.Fakes;
