name: CTF CI

on: 
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main
env:
  DOTNET_VERSION: '10.x'

jobs:
  unit_testing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Setup .NET ${{ env.DOTNET_VERSION }}
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Execute unit tests
      run: dotnet test ./tests/Application.Tests/CTF.Application.Tests.csproj -c Release

  integration_testing:
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb
        ports:
          - 3306:3306
        env:
          MARIADB_DATABASE: gamemode
          MARIADB_ROOT_PASSWORD: 123456789
        options: >-
          --name mariadb
          --health-cmd="mariadb-admin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Setup .NET ${{ env.DOTNET_VERSION }}
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Check MariaDB version
      run: docker exec mariadb mariadb --version
    - name: Create .env.test file
      run: cp ./tests/Persistence.Tests/.env.test.example ./tests/Persistence.Tests/.env.test
    - name: Execute integration tests
      run: dotnet test ./tests/Persistence.Tests/Persistence.Tests.csproj -c Release