name: CTF Deploy

on:
  workflow_dispatch:
  release:
    types: [published]

env:
  SERVER_DIRECTORY: ctf-server

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Show deployment info
        run: |
          echo "Event: ${{ github.event_name }}"
          echo "Server directory: $SERVER_DIRECTORY"
      - name: Deploy using ssh
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          envs: SERVER_DIRECTORY
          script: |
            cd $SERVER_DIRECTORY
            git checkout main
            git pull --ff-only origin main
            git status
            sudo docker compose up --build -d
            sudo docker builder prune -f
            sudo docker image prune -f