name: CTF Deploy Production

on:
  release:
    types: [published]

jobs:
  deploy:
    if: github.event.release.prerelease == false

    runs-on: ubuntu-latest
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ctf-prod
            git fetch --all --tags
            git checkout ${{ github.event.release.tag_name }}
            git status
            sudo docker compose up --build -d
            sudo docker builder prune -f
            sudo docker image prune -f